### PR TITLE
Add support for Docker Swarm

### PR DESCRIPTION
**Pull request by Xarthisius**
This is a port of @jhamrick 's work in order to enable usage of Docker Swarm instead of Docker Engine.

### CODE REVIEW

**Comment by yuvipanda** [comment]
Does this need more work to be merged? Does it still need to be merged?

**Comment by rgbkrk** [comment]
Hmmm, I'm using the dockerspawner currently with a swarm node and not needing a separate spawner. I do have to set a few options though.

**Comment by jhamrick** [comment]
@rgbkrk what options are you setting? The main differences between `SwarmSpawner` and `DockerSpawner` was that it needed to parse the container names and set the ip of the container. If that's no longer necessary, that would be awesome...

**Comment by rgbkrk** [comment]
@smashwilson had to make one change that was in https://github.com/jupyter/dockerspawner/pull/72 to use the HostIP from `docker port` output, humming right along with dockerspawner now.

**Comment by rgbkrk** [comment]
We (Carina) are also checking out overlay networks now that we support them in Carina's swarm environment (as of yesterday), so that you can have isolated networking between jupyterhub and the user notebook servers. For other swarm deployments, the code should remain the same as its still native swarm/docker under the hood - orchestration of both swarm and the overlay networks are up to the operator.

**Comment by betatim** [comment]
Is there somewhere I can follow along/contribute to for development on that (overlay for networking)?

**Comment by rgbkrk** [comment]
Here's our workshop @betatim:

https://github.com/everett-toews/jupyterhub-on-docker-swarm

Where you probably care is in the [jupyterhub-launch](https://github.com/everett-toews/jupyterhub-on-docker-swarm/tree/gh-pages/jupyterhub-launch) directory.

**Comment by rgbkrk** [comment]
To follow up, here's our `jupyterhub_config.py`:

```python
import os
import re

c = get_config()

c.JupyterHub.hub_ip = "0.0.0.0"

c.JupyterHub.spawner_class = "dockerspawner.DockerSpawner"
c.DockerSpawner.tls_verify = True
c.DockerSpawner.tls_ca = "/etc/docker/ca.pem"
c.DockerSpawner.tls_cert = "/etc/docker/server-cert.pem"
c.DockerSpawner.tls_key = "/etc/docker/server-key.pem"
c.DockerSpawner.container_ip = "0.0.0.0"
c.DockerSpawner.hub_ip_connect = os.environ["HUB_IP_CONNECT"]

c.JupyterHub.authenticator_class = "oauthenticator.GitHubOAuthenticator"

c.JupyterHub.login_url = "/hub/oauth_login"

def userlist(varname):
    """
    Interept an environment variable as a whitespace-separated list of GitHub
    usernames.
    """

    parts = re.split("\s*,\s*", os.environ[varname])
    return set([part for part in parts if len(part) > 0])

c.Authenticator.whitelist = userlist("JUPYTERHUB_USERS")
c.Authenticator.admin_users = userlist("JUPYTERHUB_ADMINS")

c.GitHubOAuthenticator.oauth_callback_url = os.environ["OAUTH_CALLBACK_URL"]
c.GitHubOAuthenticator.client_id = os.environ["GITHUB_CLIENT_ID"]
c.GitHubOAuthenticator.client_secret = os.environ["GITHUB_CLIENT_SECRET"]
```

We're using GitHubOAuthenticator, though you can use whatever you like (BYOA - Bring Your Own Auth).

For launching, this is our general setup:

```bash
#!/bin/sh
set -euo pipefail

## Environment variables you need set
# Set this to your publicly accessible IP address or DNS name
# export DNSNAME=jub.fict.io

# Comma-separated list of GitHub usernames to permit access
# export JUPYTERHUB_USERS=rgbkrk,smashwilson,carolynvs,everett-toews

# Comma-separated list of GitHub usernames of admins
# export JUPYTERHUB_ADMINS=rgbkrk,smashwilson,carolynvs,everett-toews

# Populate these from a GitHub application that you've created.
# https://github.com/settings/applications/new
# export GITHUB_CLIENT_ID=
# export GITHUB_CLIENT_SECRET=

docker build -t jupyterhub-carina .
docker pull jupyter/singleuser

# Use the head node
NODE_NAME=$(docker info | grep $(echo "${DOCKER_HOST#tcp://}" | cut -d ":" -f1) | cut -d ":" -f1 | sed -e 's/^[[:space:]]*//' )

docker run --detach \
  --name jupyterhub \
  -p 80:8000 \
  -p 8081:8081 \
  --volumes-from swarm-data:ro \
  -e JUPYTERHUB_USERS=${JUPYTERHUB_USERS} \
  -e JUPYTERHUB_ADMINS=${JUPYTERHUB_ADMINS} \
  -e DOCKER_HOST=https://${DOCKER_HOST#tcp://} \
  -e HUB_IP_CONNECT=${DNSNAME} \
  -e OAUTH_CALLBACK_URL=http://${DNSNAME}/hub/oauth_callback \
  -e GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID} \
  -e GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET} \
  -e "constraint:node==$NODE_NAME" \
  jupyterhub-carina
```

**Comment by rgbkrk** [comment]
Working swarm using the above setup:

```
$ docker ps
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                                      NAMES
d493933f6257        jupyter/singleuser   "tini -- sh /srv/sing"   11 minutes ago      Up 11 minutes       146.20.68.20:32768->8888/tcp                               c0fa2c6f-2045-4ca0-85e6-2d3addd0e135-n2/jupyter-rgbkrk
803f72a69ce9        jupyterhub-carina    "jupyterhub -f /srv/j"   12 minutes ago      Up 11 minutes       172.99.73.183:8081->8081/tcp, 172.99.73.183:80->8000/tcp   c0fa2c6f-2045-4ca0-85e6-2d3addd0e135-n1/jupyterhub
```

**Comment by rgbkrk** [comment]
Thanks for taking the time to port over the work from the SwarmSpawner @Xarthisius. We should be able to charge ahead in working on Swarm now! :smile:

**Comment by Xarthisius** [comment]
@rgbkrk what would be a canonical place to put your comment as doc for people trying to setup juphub on swarm?

**Comment by rgbkrk** [comment]
You know, we don't have any docs for DockerSpawner aside from our READMEs here. I wonder if @willingc thinks we should put it here or in https://github.com/jupyter/jupyterhub/tree/master/docs

I'm inclined to think we should update https://github.com/jupyter/jupyterhub/blob/master/docs/source/spawners.md#examples

Happy to do it or happy to merge a PR from you over there @Xarthisius. :smile:

**Comment by minrk** [comment]
Adding to the JupyterHub docs seems appropriate.

**Pull request closed without merging**
