### PR TITLE
Docker client auto version

### PR DESCRIPTION
**Pull request by richafrank**
Add version='auto' to the docker client to connect to server API versions other than the latest.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looks like me merging the other PR (#44) resulted in this one needed a rebase. Are you comfortable with doing one @richafrank?

**Comment by richafrank** [comment]
Sure thing @rgbkrk .

**Comment by richafrank** [comment]
Should be all set now.

**Comment by rgbkrk** [comment]
Looks good, sorry about that!

**Comment by richafrank** [comment]
No problem - thanks!

**Pull request merged**
